### ISSUE TITLE
RasterioIOError: Attempt to create new tiff file failed: Permission denied

### ISSUE THREAD

**Issue by SageVisions** [HakaiInstitute/kelp-o-matic#75]
I successfully ran Kelp-O-Matic at the end of August, and now I'm receiving the following error:

RasterioIOError: Attempt to create new tiff file 'C:/Users/Xxxx.Xxxxx/Desktop/DD_Kashia/KelpOMaticOutput' failed: Permission denied._ 

Any suggestions you may have would be greatly appreciated.

**Comment by tayden** [comment]
Hi @SageVisions, here's a few things to check.

1. You have enough user permissions to write to that directory? 
2. Double check that the directory you're writing to already exists. KoM won't create any new directories automatically.
3. The output location you specify via the command line tool should end with ".tif", e.g. `C:/Users/Xxxx.Xxxxx/Desktop/DD_Kashia/KelpOMaticOutput.tif`

**Comment by SageVisions** [comment]
Hi Taylor,
Number 3 was the golden nugget. Thank you very much.

**Comment by tayden** [comment]
Excellent. I'll add it to the To Do list that there should be some more helpful hints when the input or output paths don't look like as they are expected
